### ISSUE TITLE
Way to change the website between dark and light

### ISSUE THREAD

**Issue by Amauri817** [Hannahliz0/bis-card-gen#13]

**Comment by Hannahliz0** [comment]
Not doing

**Comment by Nishant9771** [comment]
### This the Javascript code for the dark and bright mode for websites.
If you already written the code for html and css then use this code by mentioning the ID then it's done.

document.getElementById('Mention your ID from HTML').addEventListener('click', function() {
    document.body.classList.toggle('dark-mode');
    saveModePreference();
});

function saveModePreference() {
    const isDarkMode = document.body.classList.contains('dark-mode');
    localStorage.setItem('darkMode', isDarkMode);
}

function loadModePreference() {
    const isDarkMode = JSON.parse(localStorage.getItem('darkMode'));
    if (isDarkMode) {
        document.body.classList.add('dark-mode');
    }
}

window.onload = loadModePreference;
